version: '3.6'

services:
  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - ./postgresql/dumps:/source/dumps
      - ./postgresql/data:/var/lib/postgresql/data
#
#  keycloak:
#    image: jboss/keycloak:latest
#    restart: always
#    ports:
#      - '7015:8081'
#    environment:
#      DB_VENDOR: postgres
#      DB_ADDR: postgres
#      DB_DATABASE: '${KEYCLOAK_DB}'
#      DB_USER: '${POSTGRES_USER}'
#      DB_SCHEMA: '${POSTGRES_SCHEMA}'
#      DB_PASSWORD: '${POSTGRES_PASSWORD}'
##      KEYCLOAK_USER: '${KEYCLOAK_USER}'
##      KEYCLOAK_PASSWORD: '${KEYCLOAK_PASSWORD}'
#      PROXY_ADDRESS_FORWARDING: "true"
#    depends_on:
#      - postgres

