-- liquibase formatted sql

-- changeset dev:1647547125809-1
CREATE TABLE authors
(
    id uuid NOT NULL,
    full_name VARCHAR(255),
    CONSTRAINT pk_authors PRIMARY KEY (id)
);

-- changeset dev:1647547125809-2
CREATE TABLE book_rating
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version INTEGER,
    book_id uuid,
    rating DECIMAL,
    number_of_ratings INTEGER,
    CONSTRAINT pk_bookrating PRIMARY KEY (id)
);

-- changeset dev:1647547125809-3
CREATE TABLE books
(
    id uuid NOT NULL,
    isbn VARCHAR(255),
    title VARCHAR(255),
    publication_date DATE,
    user_id VARCHAR(255),
    CONSTRAINT pk_books PRIMARY KEY (id)
);

-- changeset dev:1647547125809-4
CREATE TABLE books_authors
(
    book_id uuid NOT NULL,
    authors_id uuid NOT NULL
);

-- changeset dev:1647547125809-5
CREATE TABLE books_categories
(
    book_id uuid NOT NULL,
    categories_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    CONSTRAINT pk_books_categories PRIMARY KEY (book_id, categories_id)
);

-- changeset dev:1647547125809-6
CREATE TABLE category
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_category PRIMARY KEY (id)
);

-- changeset dev:1647547125809-7
ALTER TABLE authors
    ADD CONSTRAINT uc_authors_id UNIQUE (id);

-- changeset dev:1647547125809-8
ALTER TABLE book_rating
    ADD CONSTRAINT uc_bookrating_book UNIQUE (book_id);

-- changeset dev:1647547125809-9
ALTER TABLE books_authors
    ADD CONSTRAINT uc_books_authors_book UNIQUE (book_id);

-- changeset dev:1647547125809-10
ALTER TABLE books_categories
    ADD CONSTRAINT uc_books_categories_book UNIQUE (book_id);

-- changeset dev:1647547125809-11
ALTER TABLE books
    ADD CONSTRAINT uc_books_id UNIQUE (id);

-- changeset dev:1647547125809-12
ALTER TABLE book_rating
    ADD CONSTRAINT fk_bookrating_on_book FOREIGN KEY (book_id) REFERENCES books (id);

-- changeset dev:1647547125809-13
ALTER TABLE books_authors
    ADD CONSTRAINT fk_booaut_on_author FOREIGN KEY (authors_id) REFERENCES authors (id);

-- changeset dev:1647547125809-14
ALTER TABLE books_authors
    ADD CONSTRAINT fk_booaut_on_book FOREIGN KEY (book_id) REFERENCES books (id);

-- changeset dev:1647547125809-15
ALTER TABLE books_categories
    ADD CONSTRAINT fk_boocat_on_book FOREIGN KEY (book_id) REFERENCES books (id);

-- changeset dev:1647547125809-16
ALTER TABLE books_categories
    ADD CONSTRAINT fk_boocat_on_category FOREIGN KEY (categories_id) REFERENCES category (id);

